
GET http://localhost:3006/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDIyODA4NjEsImV4cCI6MTcwMjI4NDQ2MSwiYXVkIjoiNjU3NjBiYmQ5MWFhY2FjODhmZWYxNGVhIiwiaXNzIjoibW9tenp6ZS5jb20ifQ.eT1M72xlXMJ2tHcutVf-8perTaJPph0gRXEW6cmD_-0




//auth routes

### Register Route
POST http://localhost:3006/auth/register
Content-Type: application/json

{
    "email": "nikola11@ninov.org",
    "password": "Nikol@",
    "role": "user",
    "name": "Nikola"
}

### Login Route
POST http://localhost:3006/auth/login
Content-Type: application/json

{
    "email": "nikola@ninov.org",
    "password": "Nikol@"
}

### Refresh token Route
POST http://localhost:3006/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDIyODA4MjQsImV4cCI6MTczMzgzODQyNCwiYXVkIjoiNjU3NjBiYmQ5MWFhY2FjODhmZWYxNGVhIiwiaXNzIjoibW9tenp6ZS5jb20ifQ.bPZYj-tDe4NG2QIy8nR6XQn15xzXDVe-dVjbvhV9iOU"
}


### Logout Route
DELETE  http://localhost:3006/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDIyODA4NjEsImV4cCI6MTczMzgzODQ2MSwiYXVkIjoiNjU3NjBiYmQ5MWFhY2FjODhmZWYxNGVhIiwiaXNzIjoibW9tenp6ZS5jb20ifQ.n8jLAciqGIafXX3LR9G5mqhXJ2H-bKbhvQaxqxIBotk"
}

