GET http://localhost:3006/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDIyMzk1NjAsImV4cCI6MTcwMjIzOTU3NSwiYXVkIjoiNjU3NjBiYmQ5MWFhY2FjODhmZWYxNGVhIiwiaXNzIjoibW9tenp6ZS5jb20ifQ.h1saz4cZqtrO_uJAv2bCZOgzo21RBrVYfGtAp3PRDIQ




//auth routes

### Register Route
POST http://localhost:3006/auth/register
Content-Type: application/json

{
    "email": "nikola11@ninov.org",
    "password": "Nikol@",
    "role": "user",
    "name": "Nikola"
}

### Login Route
POST http://localhost:3006/auth/login
Content-Type: application/json

{
    "email": "nikola@ninov.org",
    "password": "Nikol@"
}

### Refresh token Route
POST http://localhost:3006/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDIyMzk1MzAsImV4cCI6MTczMzc5NzEzMCwiYXVkIjoiNjU3NjBiYmQ5MWFhY2FjODhmZWYxNGVhIiwiaXNzIjoibW9tenp6ZS5jb20ifQ.uYvkMzxGywsxC9aOw1_QoczSoCip559hFWPD6bqJF78"
}


### Logout Route
DELETE  http://localhost:3006/auth/logout


